name: Feature Request
description: Suggest a feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of the problem or motivation.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
      placeholder: Describe alternatives...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area of the project does this relate to?
      options:
        - Telegram Bot
        - Claude CLI Integration
        - Permission System
        - Session Management
        - Installer
        - Documentation
        - Other
    validations:
      required: true
